apiVersion: batch/v1
kind: Job
metadata:
  name: buildah-nc-build
  namespace: arc-runners
spec:
  template:
    spec:
      containers:
      - name: buildah
        image: quay.io/buildah/stable:latest
        securityContext:
          capabilities:
            add: ["SETFCAP", "FOWNER", "DAC_OVERRIDE", "CHOWN", "SETUID", "SETGID", "SYS_ADMIN"]
        command:
        - buildah
        - bud
        - --tls-verify=false
        - --file=/workspace/Dockerfile
        - --tag=reg.1u1.it:443/itoah/buildah-nc-test:latest
        - /workspace
        volumeMounts:
        - name: dockerfile-config
          mountPath: /workspace
        - name: docker-config
          mountPath: /buildah/.docker
      restartPolicy: Never
      volumes:
      - name: dockerfile-config
        configMap:
          name: dockerfile-config
      - name: docker-config
        secret:
          secretName: docker-config
  backoffLimit: 1
