apiVersion: batch/v1
kind: Job
metadata:
  name: buildah-nc-build
  namespace: arc-runners
spec:
  template:
    spec:
      containers:
      - name: buildah
        image: quay.io/buildah/stable:latest
        securityContext:
          runAsUser: 1000  # Example non-root user
          allowPrivilegeEscalation: false
          #readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]  # Start with all capabilities dropped
            add: ["CHOWN", "SETUID", "SETGID"]  # Add only necessary capabilities
        command:
        - buildah
        - bud
        - --tls-verify=false
        - --file=/workspace/Dockerfile
        - --tag=reg.1u1.it:443/itoah/buildah-nc-test:latest
        - /workspace
        volumeMounts:
        - name: dockerfile-config
          mountPath: /workspace
        - name: docker-config
          mountPath: /buildah/.docker
      restartPolicy: Never
      volumes:
      - name: dockerfile-config
        configMap:
          name: dockerfile-config
      - name: docker-config
        secret:
          secretName: docker-config
  backoffLimit: 1
