apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
  #namespace: arc-systems
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - --dockerfile=/workspace/Dockerfile
        - --context=dir:///workspace
        - --destination=reg.1u1.it:443/itoah/kaniko-test:latest
        - --skip-tls-verify
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: docker-config
          mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
      - name: workspace
        emptyDir: {}
      - name: docker-config
        secret:
          secretName: docker-config
  backoffLimit: 1
