apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-nc-build
  namespace: arc-runners
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - --dockerfile=/workspace/Dockerfile
        - --context=dir:///workspace
        - --destination=reg.1u1.it:443/itoah/kaniko-nc-test:latest
        - --skip-tls-verify
        volumeMounts:
        #- name: kaniko-workspace              #### In case of PV
        #  mountPath: /workspace               #### In case of PV
        - name: dockerfile-config
          mountPath: /workspace
        #  mountPath: /workspace/Dockerfile    #### In case of PV
        #  subPath: Dockerfile                 #### In case of PV
        - name: docker-config
          mountPath: /kaniko/.docker
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - ci-runner
      restartPolicy: Never
      volumes:
      - name: dockerfile-config
        configMap:
          name: dockerfile-config
      - name: docker-config
        secret:
          secretName: docker-config
      #- name: kaniko-workspace                 #### In case of PV
      #  persistentVolumeClaim:                 #### In case of PV
      #    claimName: kaniko-pvc                #### In case of PV
  backoffLimit: 1
