apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-nc-build
  namespace: arc-runners
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Pre-build cleanup
          echo "Cleaning up pre-existing temporary files..."
          rm -rf /workspace/*
        resources:
          requests:
            ephemeral-storage: "4Gi"  # Adjust this value based on your needs
          limits:
            ephemeral-storage: "10Gi"  # Limit can be higher to prevent excessive usag
        args:
        - --dockerfile=/workspace/Dockerfile
        - --context=dir:///workspace
        - --destination=reg.1u1.it:443/itoah/kaniko-nc-test:latest
        - --skip-tls-verify
        volumeMounts:
        - name: dockerfile-config
          mountPath: /workspace
        - name: docker-config
          mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
      - name: dockerfile-config
        configMap:
          name: dockerfile-config
      - name: docker-config
        secret:
          secretName: docker-config
  backoffLimit: 1
