apiVersion: batch/v1
kind: Job
metadata:
  name: create-minikube-with-kaniko
  namespace: arc-runners
spec:
  template:
    spec:
      initContainers:
      - name: init
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          echo "Installing minikube..."
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
          echo "Starting minikube"
          minikube start   
          echo "Creating Secret"
          mkdir -p $HOME/.docker
          echo "{\"auths\":{\"reg.1u1.it:443\":{\"username\":\"${{ secrets.HARBOR_USERNAME }}\",\"password\":\"${{ secrets.HARBOR_PASSWORD }}\"}}}" > $HOME/.docker/config.json
          kubectl create secret generic docker-sec-config --from-file=config.json=$HOME/.docker/config.json
          kubectl get secret docker-sec-config
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - --dockerfile=./.devcontainer/Dockerfile 
        - --context=dir:.
        - --destination=reg.1u1.it:443/itoah/hidrive-nc-test:latest
        - --skip-tls-verify
        volumeMounts:      
        - name: docker-sec-config
          mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
      - name: docker-sec-config
        secret:
          secretName: docker-sec-config
  backoffLimit: 1
