on:
  workflow_dispatch:

name: Buildah-image-builder-and-push
jobs:
  build-and-push-using-buildah:
    runs-on: arc-runners-nextcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: IONOS-Productivity/nc-server
          ref: master

      - name: Package Code
        run: |
          mkdir -p /tmp/nc-server
          cp -r . /tmp/nc-server
          cd /tmp/nc-server
          tar -czf /tmp/nc-server.tar.gz .

      #- name: Upload Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: nc-server-package
      #    path: /tmp/nc-server.tar.gz   

      #- name: Login to Harbor
      #  run: |
      #    echo ${{ secrets.HARBOR_PASSWORD }} | buildah login reg.1u1.it:443 -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Install Buildah
        run: | 
          sudo apt-get -qq -y install buildah  
        
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: reg.1u1.it:443/itoah/buildah-nc-test
          tags: latest
          containerfiles: |
            /tmp/nc-server/.devcontainer/Dockerfile 
          tls-verify: false    
          
      - name: Tasks Completed
        run: |
          echo "All tasks completed gracefully."
