on:
  workflow_dispatch:

name: Curl-and-Docker-Installation
jobs:
  curl:
    runs-on: arc-runners-nextcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Curl and Docker
        run: |
          echo "The current user is: $current_user"
          echo "The current home is: $current_home"
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates
          curl --version

      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Verify Docker installation
        run: |
          docker run hello-world
          docker --version  
          
