on:
  workflow_dispatch:

name: Curl-Installation
jobs:
  curl:
    runs-on: arc-runners-nextcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Curl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Use Curl
        run: curl --version
