on:
  workflow_dispatch:

name: Curl-and-Kaniko-Installation
jobs:
  curl:
    runs-on: arc-runners-nextcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Curl
        run: |
          echo "The current user is: $current_user"
          echo "The current home is: $current_home"
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates
          curl --version
          which curl

      - name: Install Kaniko
        run: |
          mkdir -p $HOME/.docker
          echo "{\"auths\":{\"reg.1u1.it:443\":{\"username\":\"${{ secrets.HARBOR_USERNAME }}\",\"password\":\"${{ secrets.HARBOR_PASSWORD }}\"}}}" > $HOME/.docker/config.json
          #echo "{\"auths\":{\"$REGISTRY_URL\":{\"username\":\"$USERNAME\",\"password\":\"$PASSWORD\"}}}" > $HOME/.docker/config.json
          curl -LO https://github.com/GoogleContainerTools/kaniko/releases/download/v1.6.0/executor
          chmod +x executor
          sudo mv executor /usr/local/bin/kaniko
          which kaniko

      - name: Add Harbor Registry Certificate
        run: |
          sudo mkdir -p /etc/docker/certs.d/reg.1u1.it:443
          echo "${{ secrets.HARBOR_CERTIFICATE }}" | sudo tee /etc/docker/certs.d/reg.1u1.it:443/ca.crt
          
      - name: Create Dockerfile for Test Image
        run: |
          echo "FROM alpine:latest" > Dockerfile
          echo "RUN echo 'Hello, Kaniko!'" >> Dockerfile

      - name: Login to Harbor
        run: |
          echo ${{ secrets.HARBOR_PASSWORD }} | docker login reg.1u1.it:443 -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build and Push Image with Kaniko
        run: |
          /usr/local/bin/kaniko \
            --dockerfile=Dockerfile \
            --context=dir://. \
            --destination=reg.1u1.it:443/itoah/kaniko-test:latest
            #--skip-tls-verify
