on:
  workflow_dispatch:

name: Curl-Installation
jobs:
  curl:
    runs-on: arc-runners-nextcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup curl
        uses: kordlib/setup-curl@v1.0.0
