on:
  workflow_dispatch:

name: Curl-and-Kaniko-Installation
jobs:
  curl:
    runs-on: arc-runners-nextcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Curl
        run: |
          echo "The current user is: $current_user"
          echo "The current home is: $current_home"
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates
          curl --version

      - name: Install Kaniko
        run: |
          mkdir -p $HOME/.docker
          echo "{\"auths\":{\"reg.1u1.it:443\":{\"username\":\"${{ secrets.HARBOR_USERNAME }}\",\"password\":\"${{ secrets.HARBOR_PASSWORD }}\"}}}" > $HOME/.docker/config.json
          curl -LO https://github.com/GoogleContainerTools/kaniko/releases/download/v1.6.0/executor-linux-amd64
          chmod +x executor-linux-amd64
          sudo mv executor-linux-amd64 /usr/local/bin/kaniko
          ls -l /usr/local/bin/kaniko

      - name: Add Harbor Registry Certificate
        run: |
          sudo mkdir -p /etc/docker/certs.d/reg.1u1.it:443
          echo "${{ secrets.HARBOR_CERTIFICATE }}" | sudo tee /etc/docker/certs.d/reg.1u1.it:443/ca.crt
          
      - name: Create Dockerfile for Test Image
        run: |
          echo "FROM alpine:latest" > Dockerfile
          echo "RUN echo 'Hello, Kaniko!'" >> Dockerfile

      - name: Login to Harbor
        run: |
          echo ${{ secrets.HARBOR_PASSWORD }} | docker login reg.1u1.it:443 -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build and Push Image with Kaniko
        run: |
          docker run \
            -v $HOME/.docker:/kaniko/.docker \
            -v $(pwd):/workspace \
            gcr.io/kaniko-project/executor:latest \
            --destination=reg.1u1.it:443/itoah/kaniko-test:latest
            #--skip-tls-verify
          echo "Image is pushed to the Registry"
            
      - name: Verify Image Push
        run: |
          echo ${{ secrets.HARBOR_PASSWORD }} | docker login reg.1u1.it:443 -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
          docker pull reg.1u1.it:443/itoah/kaniko-test:latest
          echo "image pulled successfully"
