on:
  workflow_dispatch:

name: Kaniko-Build-and-Push
jobs:
  build-and-push:
    runs-on: arc-runners-nextcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        id: install
        with:
          version: 'latest'         

      - name: Create Docker Config for Kaniko
        run: |
          mkdir -p $HOME/.docker
          echo "{\"auths\":{\"reg.1u1.it:443\":{\"username\":\"${{ secrets.HARBOR_USERNAME }}\",\"password\":\"${{ secrets.HARBOR_PASSWORD }}\"}}}" > $HOME/.docker/config.json
          kubectl create secret generic docker-config --from-file=config.json=$HOME/.docker/config.json

      - name: Create Dockerfile for Test Image
        run: |
          echo "FROM alpine:latest" > Dockerfile
          echo "RUN echo 'Hello, Kaniko!'" >> Dockerfile

      - name: Apply Kaniko Job
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_LOCAL_K8s }}
        run: |
          kubectl apply -f kaniko-job.yaml

      - name: Monitor Job Status
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_LOCAL_K8s }}
        run: |
          echo "Monitoring kaniko build job"
          kubectl wait --for=condition=complete job/kaniko-build-job --namespace=arc-systems --timeout=600s
