on:
  workflow_dispatch:

name: Kaniko-Build-and-Push
jobs:
  build-and-push:
    runs-on: arc-runners-nextcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        id: install
        with:
          version: 'latest'  

      - name: Setup KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Create Docker Config for Kaniko
        run: |
          mkdir -p $HOME/.docker
          echo "{\"auths\":{\"reg.1u1.it:443\":{\"username\":\"${{ secrets.HARBOR_USERNAME }}\",\"password\":\"${{ secrets.HARBOR_PASSWORD }}\"}}}" > $HOME/.docker/config.json
          set +e
          kubectl get secret docker-config
          if [ $? -ne 0 ]; then
            kubectl create secret generic docker-config --from-file=config.json=$HOME/.docker/config.json --namespace=arc-systems
          else
            echo "Secret docker-config already exists, skipping creation."
          fi
          set -e
          
      - name: Use Dockerfile from Repository
        run: |
          cp ./Dockerfile ./workspace/Dockerfile

      - name: Apply Kaniko Job
        run: |
          kubectl apply -f kaniko-job.yaml

      - name: Monitor Job Status
        run: |
          echo "Monitoring kaniko build job"
          kubectl wait --for=condition=complete job/kaniko-build --timeout=600s
