name: Fork NextCloud and Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fork-and-build:
    runs-on: arc-runner-nc-fork

    steps:    
      - name: Install Git
        run: |
          if ! command -v git &> /dev/null
          then
            echo "Git not found, installing..."
            sudo apt-get update
            sudo apt-get install -y git
          else
            echo "Git is already installed"
          fi
      - name: Increase Git Buffer Size
        run: |
          git config --global http.postBuffer 524288000
          git config --global http.maxRequestBuffer 1048576000
          git config --global core.compression 0 # Disables compression
          
      - name: Fork NextCloud Repository Master Branch Only
        run: |
          retries=0
          while [ $retries -lt 5 ]; do
            # Use shallow clone to reduce data transfer and continue on errors, logging outputs
            git clone --single-branch --branch "master" --depth="1" https://github.com/nextcloud/server.git && break || {
              echo "Failed to clone, retrying..."
              sleep 15
            }
            retries=$((retries + 1))
          done
          if [ $retries -eq 5 ]; then
            echo "Failed to clone the repository after 5 attempts"
            exit 1
          fi

      - name: Change Remote and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd server
          ls -la
          git remote add private https://x-access-token:${GH_PAT}@github.com/muhali-ionos/nc.git
          git push private master:main -f
          
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: muhali-ionos/nc.git
          ref: main
