name: Fork NextCloud and Build Docker Image

on:
  workflow_dispatch:

jobs:
  fork-and-build:
    runs-on: arc-runner-nc-fork

    steps:    
      - name: Install Git
        run: |
          if ! command -v git &> /dev/null
          then
            echo "Git not found, installing..."
            sudo apt-get update
            sudo apt-get install -y git
          else
            echo "Git is already installed"
          fi
          
      - name: Fork NextCloud Repository Master Branch Only
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone --single-branch --branch master https://github.com/nextcloud/server.git
          cd server
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/muhali-ionos/nc.git
          git push --set-upstream origin master  
          
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: muhali-ionos/nc.git
          ref: main
