on:
  workflow_dispatch:

name: New-Modified-Hi-Drive-Build-NC
jobs:
  build-and-push:
    runs-on: self-hosted-nc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print contents
        run: |
          pwd
          ls -la
          #sudo apt-get update && sudo apt-get install -y make
          #make --version  

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: IONOS-Productivity/nc-server
          ref: master

      #- name: Package Code
      #  run: |
      #    pwd
      #    ls -la
      #    #mkdir -p /tmp/nc-server
      #    #cp -r . /tmp/nc-server
      #    #cd /tmp/nc-server
      #    tar -czf /tmp/nc-server.tar.gz ../nc/
      #    ls -lh /tmp/nc-server.tar.gz

      #- name: Upload Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: nc-server-package
      #    path: /tmp/nc-server.tar.gz   

      - name: Set up Docker credentials
        run: |
          #pwd
          #ls -la
          sudo mkdir -p /kaniko/.docker 
          sudo ls -l /kaniko/.docker
          sudo bash -c 'cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "https://reg.1u1.it:443/": {
                "auth": "$(echo -n "${{ secrets.HARBOR_USERNAME }}:${{ secrets.HARBOR_PASSWORD }}" | base64)"
              }
            }
          }
          EOF'
          echo "listing contents"
          sudo ls -l /kaniko/.docker/
          #mkdir -p /kaniko/.docker 
          #echo "{\"auths\":{\"reg.1u1.it:443\":{\"username\":\"${{ secrets.HARBOR_USERNAME }}\",\"password\":\"${{ secrets.HARBOR_PASSWORD }}\"}}}" > /tmp/kaniko/.docker/config.json
          echo "checking contents"
          sudo cat /kaniko/.docker/config.json
          
      - name: Build and Push Docker Image with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:v1.20.0
        with:
          args: >
            --dockerfile=./.devcontainer/Dockerfile 
            --context=.
            --destination=reg.1u1.it:443/itoah/hidrive-nc-test:latest
            --skip-tls-verify
  
        
            
