on:
  workflow_dispatch:

name: New-Modified-Hi-Drive-Build-NC
jobs:
  build-and-push:
    runs-on: self-hosted-nc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print contents
        run: |
          pwd
          ls -la
          #sudo apt-get update && sudo apt-get install -y make
          #make --version  

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: IONOS-Productivity/nc-server
          ref: master

      #- name: Package Code
      #  run: |
      #    pwd
      #    ls -la
      #    #mkdir -p /tmp/nc-server
      #    #cp -r . /tmp/nc-server
      #    #cd /tmp/nc-server
      #    tar -czf /tmp/nc-server.tar.gz ../nc/
      #    ls -lh /tmp/nc-server.tar.gz

      #- name: Upload Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: nc-server-package
      #    path: /tmp/nc-server.tar.gz   

      - name: Create and Apply Kaniko Job
        run: |
          # Delete existing job if exists
          #kubectl delete job kaniko-nc-build-push --namespace=arc-runners --ignore-not-found
          pwd
          ls -l
          kubectl apply -f minikube-kaniko.yaml         

      - name: Monitor Job Status
        run: |
          echo "Monitoring Nextcloud build job."
          kubectl wait --for=condition=complete job/Create Minikube Environment with Kaniko --timeout=1200s
          echo "Nextcloud Image is pushed to the Harbor Registry."
  
        
            
