on:
  workflow_dispatch:

name: New-Modified-Hi-Drive-Build-NC
jobs:
  build-and-push:
    runs-on: self-hosted-nc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print contents
        run: |
          pwd
          ls -la
      #    sudo apt-get update && sudo apt-get install -y make
      #    make --version  

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: IONOS-Productivity/nc-server
          ref: master

      - name: Package Code
        run: |
          pwd
          ls -la
      #    tar -czf /tmp/nc-server.tar.gz ../nc/
      #    ls -lh /tmp/nc-server.tar.gz

      #- name: Upload Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: nc-server-package
      #    path: /tmp/nc-server.tar.gz  

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        id: install
        with:
          version: 'latest'  
          
      - name: Create Docker Secret Config for Kaniko
        run: |
          mkdir -p $HOME/.docker
          AUTH="$(echo -n "${{ secrets.HARBOR_USERNAME }}:${{ secrets.HARBOR_PASSWORD }}" | base64)"
          echo "{\"auths\":{\"reg.1u1.it:443\":{\"auth\":\"${AUTH}\"}}}" > $HOME/.docker/config.json
          set +e
          kubectl get secret docker-sec-config -n arc-runners
          if [ $? -ne 0 ]; then
            kubectl create secret generic docker-sec-config --from-file=config.json=$HOME/.docker/config.json --namespace=arc-runners
          else
            echo "docker-sec-config already exists, skipping creation."
          fi
          set -e
        
      #- name: Create Dockerfile for Kaniko
      #  run: |
      #    set +e
      #    kubectl get secret docker-file-config
      #    if [ $? -ne 0 ]; then
      #      #kubectl create configmap docker-file-config --from-file=Dockerfile=./.devcontainer/Dockerfile --namespace=arc-runners  
      #      kubectl create secret generic docker-file-config --from-file=Dockerfile=./.devcontainer/Dockerfile --namespace=arc-runners
      #    else
      #      echo "docker-file-config already exists, skipping creation."
      #    fi
      #    set -e 

      - name: Identify Runner Pod and Node
        id: identify-resources
        run: |
          POD_NAME=$(kubectl get pods -n arc-runners -l app.kubernetes.io/instance=self-hosted-nc -o jsonpath='{.items[0].metadata.name}')
          NODE_NAME=$(kubectl get pod ${POD_NAME} -n arc-runners -o jsonpath='{.spec.nodeName}')
          echo "POD_NAME=${POD_NAME}" >> $GITHUB_ENV
          echo "NODE_NAME=${NODE_NAME}" >> $GITHUB_ENV
            
      - name: Create and Apply Kaniko Job
        run: |
          set +e
          # Check if the job exists
          kubectl get job kaniko-nc-build-push -n arc-runners
          if [ $? -eq 0 ]; then
            echo "Job kaniko-nc-build-push exists, deleting it..."
            kubectl delete job kaniko-nc-build-push -n arc-runners
          fi
      
          # Create a new job
          echo "
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: kaniko-nc-build-push
            namespace: arc-runners
          spec:
            template:
              spec:                
                nodeSelector:
                  kubernetes.io/os: linux
                  node-restriction.kubernetes.io/reserved-for: cert-manager  
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                          - ${NODE_NAME}
                initContainers:
                - name: git-clone
                  image: alpine/git
                  args: 
                  - clone
                  - --depth=1
                  - 'https://github.com/IONOS-Productivity/nc-server.git'
                  - /workspace
                  volumeMounts:
                  - name: build-context
                    mountPath: /workspace
                containers:
                - name: kaniko
                  image: gcr.io/kaniko-project/executor:latest
                  #image: gcr.io/kaniko-project/executor:debug
                  command:
                  #- /bin/sh
                  #- -c
                  #- |
                  #  echo "Listing /workspace contents:"; 
                  #  ls -la /workspace;
                  #  echo "Sleeping for debug...";
                  #  sleep 3600
                  args:
                  - --dockerfile=/workspace/.devcontainer/Dockerfile
                  - --context=dir:///workspace
                  - --destination=reg.1u1.it:443/itoah/hidrive-nc-test:latest
                  - --skip-tls-verify
                  volumeMounts:
                  - name: build-context
                    mountPath: /workspace                     
                  - name: docker-sec-config
                    mountPath: /kaniko/.docker
                restartPolicy: Never
                volumes:
                - name: build-context
                  emptyDir: {}              
                #  secret:
                #    secretName: docker-file-config
                - name: docker-sec-config
                  secret:
                    secretName: docker-sec-config
            backoffLimit: 1
          " | kubectl apply -f -
          set -e
    
      - name: Monitor Job Status
        run: |
          echo "Monitoring Nextcloud build job."
          kubectl wait --for=condition=complete job/kaniko-nc-build-push --timeout=1200s
          echo "Nextcloud Image is pushed to the Harbor Registry."   
            
      - name: Delete Kaniko Job
        run: |
          kubectl delete job kaniko-nc-build-push --namespace=arc-runners --ignore-not-found
          kubectl delete secret -n arc-runners docker-sec-config --ignore-not-found
          #kubectl delete secret -n arc-runners docker-file-config --ignore-not-found
          echo "All tasks completed gracefully."
