name: Package NextCloud Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  package-code:
    runs-on: self-hosted

    steps:
      - name: Install Git
        run: |
          if ! command -v git &> /dev/null
          then
            echo "Git not found, installing..."
            sudo apt-get update
            sudo apt-get install -y git
          else
            echo "Git is already installed"
          fi
      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: IONOS-Productivity/nc-server
          ref: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
        with: 
           buildkitd-flags: --debug

      #- name: Set up containerd
      #  uses: crazy-max/ghaction-setup-containerd@v2
        
      #- name: Build Docker Image
      #  run: |
      #    cd /tmp/nc-server/.devcontainer
      #    docker build --network host -t muhali/nextcloud:latest .

      - name: Login to Harbor
        run: |
          echo ${{ secrets.HARBOR_PASSWORD }} | docker login reg.1u1.it -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      #- name: Push Docker Image to Harbor
      #  run: |
      #    docker tag muhali/nextcloud:latest reg.1u1.it/nc/nextcloud:latest
      #    docker push reg.1u1.it/nc/nextcloud:latest

      - name: Package Code
        run: |
          mkdir -p /tmp/nc-server
          cp -r . /tmp/nc-server
          cd /tmp/nc-server
          tar -czvf /tmp/nc-server.tar.gz .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nc-server-package
          path: /tmp/nc-server.tar.gz    
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          #context: .
          push: true
          tags: reg.1u1.it/nc-image-test:latest
