on:
  workflow_dispatch:

name: docker-installation
jobs:
  docker:
    runs-on: arc-runner-nc-fork
    steps:
    - name: Setup curl
      uses: wei/curl@v1

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    
    - run: |
        set -x

        docker version

        docker run --rm hello-world
