on:
  workflow_dispatch:

name: docker-installation
jobs:
  ci:
    runs-on: arc-runner-nc-fork
    steps:
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - run: |
        set -x

        docker version

        docker run --rm hello-world
