on:
  workflow_dispatch:

name: docker-installation
jobs:
  buildx:
    runs-on: arc-runners-nextcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker
        run: |       
          sudo apt update --fix-missing
          sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          systemctl status docker
          docker version
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - name: Build
        run: |
          systemctl status docker
          docker version
