on:
  workflow_dispatch:

name: docker-installation
jobs:
  test-image:
    runs-on: arc-runner-nc-fork
    steps:
      - uses: actions/checkout@v4
      - name: Check that the image builds
        run: docker build . --file Dockerfile
